version: "3"
services:
  client:
    build: ./client
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    environment:
      - NODE_ENV=development
    depends_on:
      - server
  server:
    build: ./server
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - ./server/src:/app/src
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
  mongo:
    image: mongo
    expose:
      - 27017
